class LanguageService:
    current_lang = "tr"

    TRANSLATIONS = {
        "tr": {
            "app_title": "Class Tool - Akıllı Tahta Öğrenci Takip [Sürüm 1.2.1]",
            "roster": "📋 Öğrenci Listesi",
            "seating": "🪑 Oturma Planı",
            "groups": "🧩 Akıllı Gruplar",
            "homework": "📅 Ödev Planlayıcı",
            "analytics": "📈 Analizler",
            "help_guide": "❓ Kullanım Kılavuzu",
            "dark_mode": "🌙 Koyu Mod",
            "light_mode": "☀️ Açık Mod",
            "change_pin": "⚙️ Şifre Değiştir",
            "timer": "⏳ Kronometre",
            "class_mgmt": "🏫 Sınıf Yönetimi",
            "data_ops": "📥 Veri İşlemleri",
            "lesson_part": "⚡ Ders & Katılım",
            "student_tools": "🛠️ Öğrenci Araçları",
            "new_class": "➕ Yeni Sınıf",
            "class_notes": "📌 Sınıf Notları",
            "delete_class": "🗑️ Sınıfı Sil",
            "add_student": "👤 Öğrenci Ekle",
            "import_excel": "📊 Excel'den Al",
            "import_text": "📝 Yapay Zeka Tarayıcı",
            "export_excel": "📥 Rapor İndir (Excel)",
            "oral_grade_btn": "📊 Sözlü Notu Hesapla",
            "correct": "✅ Doğru",
            "wrong": "❌ Yanlış",
            "pass": "⏭️ Pas",
            "random_pick": "🎲 Rastgele Seç",
            "edit_info": "✏️ Bilgileri Düzenle",
            "detailed_score": "⭐ Detaylı Puanla",
            "profile_notes": "👤 Özel Profil & Notlar",
            "delete_student": "🗑️ Öğrenciyi Sil",
            "unassigned": "📋 Yerleşmeyen Öğrenciler",
            "save_layout": "💾 Kaydet",
            "build_layout": "⚙️ Kur",
            "row_lbl": "Sıra:",
            "depth_lbl": "Derinlik:",
            "seat_lbl": "Masa Koltuk:",
            "teacher_desk": "🟢 Akıllı Tahta / Öğretmen Masası",
            "settings_title": "⚙️ Güvenlik ve Veri Ayarları",
            "pin_title": "Şifre Değiştir",
            "usb_title": "Güvenli USB Anahtar Yöneticisi",
            "backup_title": "Taşınabilir Veri Aktarımı",
            "no": "No",
            "first_name": "Ad",
            "last_name": "Soyad",
            "gender": "Cinsiyet",
            "female": "Kız",
            "male": "Erkek",
            "group_title": "🧩 Akıllı Grup Oluşturucu",
            "rules_btn": "⚙️ Kurallar",
            "generate_groups": "🧩 Grup Oluştur",
            "save_groups": "💾 Grupları Kaydet",
            "rules_dialog_title": "⚙️ Gruplandırma Kuralları",
            "equal_gender": "Eşit Cinsiyet Dağılımı",
            "balance_traits": "Öğrenci Profillerini Dengele",
            "apply_rules": "💾 Kuralları Uygula",
            "homework_title": "📅 Ödev Planlayıcı & Takip",
            "assign_homework": "📌 Seçilen Güne Ödev Ata",
            "select_date_prompt": "📋 Ödevleri görmek için bir tarih seçin",
            "done_btn": "✅ Yapıldı",
            "missing_btn": "❌ Eksik",
            "save_status": "💾 Ödev Durumlarını Kaydet",
            "analytics_title_hw_done": "✅ Yapılan Ödevler",
            "analytics_title_hw_miss": "❌ Eksik Ödevler",
            "analytics_title_total": "📋 Toplam Öğrenci",
            "refresh_data": "🔄 Verileri Yenile",
            "net_part": "Net Katılım",
            "net_beh": "Net Davranış",
            "login_title": "🔑 Şifre Girin veya USB Anahtar Takın",
            "unlock_sys": "Sistemin Kilidini Aç",
            "setup_title": "🚀 İlk Kurulum - Yönetici Şifresi",
            "new_pin": "Yeni Şifre",
            "confirm_pin": "Şifreyi Onayla",
            "save_start": "💾 Kaydet & Başlat",
            "timer_title": "Akıllı Tahta Kronometre",
            "countdown": "Geri Sayım",
            "stopwatch": "Kronometre",
            "start": "▶ Başlat",
            "pause": "⏸ Duraklat",
            "reset": "⏹ Sıfırla",
            "current_pin": "Mevcut Şifre",
            "update_pin": "💾 Şifreyi Güncelle",
            "usb_key_btn": "🔑 Takılı USB'yi Güvenlik Anahtarım Yap",
            "export_backup": "📤 Yedek Dışarı Aktar",
            "import_backup": "📥 Yedek İçe Aktar",
            "class_name": "Sınıf Adı:",
            "academic_year": "Eğitim Yılı:",
            "save_class": "Sınıfı Kaydet",
            "cancel": "İptal",
            "save": "Kaydet",
            "success": "Başarılı",
            "warning": "Uyarı",
            "error": "Hata",
            "spin": "🎡 Çarkı Çevir!",
            "evaluation": "Değerlendirme / Durum:",
            "fill_all_fields": "Lütfen tüm alanları doldurun.",
            "select_student_first": "Lütfen listeden bir öğrenci seçin.",
            "select_class_first": "Lütfen önce bir sınıf seçin.",
            "confirm_delete_class": "'{class_name}' sınıfını silmek istediğinize emin misiniz?",
            "confirm_delete_student": "{student_name} adlı öğrenciyi silmek istediğinize emin misiniz?",
            "usb_not_found_title": "USB Bulunamadı",
            "usb_not_found_msg": "Lütfen önce bir USB disk takın (C/D harici sürücü).",
            "curr_pin_wrong": "Mevcut şifre hatalı.",
            "pin_short": "Yeni şifre en az 4 haneli olmalıdır.",
            "pins_mismatch": "Yeni şifreler eşleşmiyor.",
            "pin_updated": "Şifre başarıyla güncellendi!",
            "guide_topics_title": "📚 Kılavuz Başlıkları",
            "guide_topics": [
                "🚀 Başlangıç ve Temel Mantık",
                "🏫 Sınıf ve Öğrenci İşlemleri",
                "🪑 Oturma Planı Nasıl Yapılır?",
                "🧩 Akıllı Gruplar Oluşturma",
                "⚡ Derse Katılım ve Çarkıfelek",
                "📊 Raporlar ve Sözlü Notu",
                "⚙️ Güvenlik (USB) ve Yedekleme",
                "💻 Geliştirici & İletişim"
            ]
        },
        "en": {
            "app_title": "Class Tool - Smart Board Tracker [v1.2.1]",
            "roster": "📋 Student Roster",
            "seating": "🪑 Seating Chart",
            "groups": "🧩 Smart Groups",
            "homework": "📅 Homework Planner",
            "analytics": "📈 Analytics",
            "help_guide": "❓ User Guide",
            "dark_mode": "🌙 Dark Mode",
            "light_mode": "☀️ Light Mode",
            "change_pin": "⚙️ Change PIN",
            "timer": "⏳ Timer / Stopwatch",
            "class_mgmt": "🏫 Class Management",
            "data_ops": "📥 Data Operations",
            "lesson_part": "⚡ Lesson & Participation",
            "student_tools": "🛠️ Student Tools",
            "new_class": "➕ New Class",
            "class_notes": "📌 Class Notes",
            "delete_class": "🗑️ Delete Class",
            "add_student": "👤 Add Student",
            "import_excel": "📊 Import from Excel",
            "import_text": "📝 AI Scanner",
            "export_excel": "📥 Export Report (Excel)",
            "oral_grade_btn": "📊 Calculate Oral Grade",
            "correct": "✅ Correct",
            "wrong": "❌ Wrong",
            "pass": "⏭️ Pass",
            "random_pick": "🎲 Pick Random",
            "edit_info": "✏️ Edit Info",
            "detailed_score": "⭐ Detailed Scoring",
            "profile_notes": "👤 Private Profile & Notes",
            "delete_student": "🗑️ Delete Student",
            "unassigned": "📋 Unassigned Students",
            "save_layout": "💾 Save Layout",
            "build_layout": "⚙️ Build",
            "row_lbl": "Blocks:",
            "depth_lbl": "Rows:",
            "seat_lbl": "Seats/Desk:",
            "teacher_desk": "🟢 Smart Board / Teacher Desk",
            "settings_title": "⚙️ Security & Data Settings",
            "pin_title": "Change Access PIN",
            "usb_title": "Security USB Key Manager",
            "backup_title": "Portable Data Transfer",
            "no": "No",
            "first_name": "First Name",
            "last_name": "Last Name",
            "gender": "Gender",
            "female": "Female",
            "male": "Male",
            "group_title": "🧩 Smart Group Generator",
            "rules_btn": "⚙️ Rules",
            "generate_groups": "🧩 Generate Groups",
            "save_groups": "💾 Save Groups",
            "rules_dialog_title": "⚙️ Group Generation Rules",
            "equal_gender": "Equal Gender Distribution",
            "balance_traits": "Balance Student Profiles",
            "apply_rules": "💾 Apply Rules",
            "homework_title": "📅 Homework Planner & Assign",
            "assign_homework": "📌 Assign Homework to Selected Date",
            "select_date_prompt": "📋 Select a date to view homeworks",
            "done_btn": "✅ Done",
            "missing_btn": "❌ Missing",
            "save_status": "💾 Save Homework Statuses",
            "analytics_title_hw_done": "✅ HW Done",
            "analytics_title_hw_miss": "❌ HW Missing",
            "analytics_title_total": "👥 Total Students",
            "refresh_data": "🔄 Refresh Data",
            "net_part": "Net Participation",
            "net_beh": "Net Behavior",
            "login_title": "🔑 Enter PIN or Insert USB Key",
            "unlock_sys": "Unlock System",
            "setup_title": "🚀 First Time Setup - Master Password",
            "new_pin": "New PIN",
            "confirm_pin": "Confirm PIN",
            "save_start": "💾 Save & Start",
            "timer_title": "Smart Board Timer",
            "countdown": "Countdown",
            "stopwatch": "Stopwatch",
            "start": "▶ Start",
            "pause": "⏸ Pause",
            "reset": "⏹ Reset",
            "current_pin": "Current PIN",
            "update_pin": "💾 Update PIN",
            "usb_key_btn": "🔑 Make Connected USB My Security Key",
            "export_backup": "📤 Export Backup",
            "import_backup": "📥 Import Backup",
            "class_name": "Class Name:",
            "academic_year": "Academic Year:",
            "save_class": "Save Class",
            "cancel": "Cancel",
            "save": "Save",
            "success": "Success",
            "warning": "Warning",
            "error": "Error",
            "spin": "🎡 Spin Wheel!",
            "evaluation": "Evaluation / Status:",
            "fill_all_fields": "Please fill in all fields.",
            "select_student_first": "Please select a student from the list first.",
            "select_class_first": "Please select a class first.",
            "confirm_delete_class": "Are you sure you want to delete class '{class_name}'?",
            "confirm_delete_student": "Are you sure you want to delete student {student_name}?",
            "usb_not_found_title": "No USB Found",
            "usb_not_found_msg": "Please insert a USB flash drive first (Drive other than C/D).",
            "curr_pin_wrong": "Current PIN is incorrect.",
            "pin_short": "New PIN must be at least 4 digits.",
            "pins_mismatch": "New PINs do not match.",
            "pin_updated": "PIN updated successfully!",
            "guide_topics_title": "📚 Guide Contents",
            "guide_topics": [
                "🚀 Getting Started & Basics",
                "🏫 Class & Student Management",
                "🪑 How to Create Seating Chart?",
                "🧩 Creating Smart Groups",
                "⚡ Lesson Participation & Wheel",
                "📊 Reports & Oral Grades",
                "⚙️ Security (USB) & Backups",
                "💻 Developer & Contact"
            ]
        }
    }

    @classmethod
    def get(cls, key):
        lang_dict = cls.TRANSLATIONS.get(cls.current_lang, cls.TRANSLATIONS["tr"])
        return lang_dict.get(key, key)

    @classmethod
    def set_language(cls, lang_code):
        if lang_code in ["tr", "en"]:
            cls.current_lang = lang_code